name: subby
description: "Subby - 구독 관리 앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Drift (SQLite ORM)
  drift: ^2.26.0
  drift_flutter: ^0.2.4

  # UUID 생성
  uuid: ^4.5.1

  # HTTP (환율 API)
  http: ^1.3.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_database: ^12.1.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Drift 코드 생성
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: NanumSquareNeo
      fonts:
        - asset: assets/fonts/NanumSquareNeo-aLt.ttf
          weight: 300
        - asset: assets/fonts/NanumSquareNeo-bRg.ttf
          weight: 400
        - asset: assets/fonts/NanumSquareNeo-cBd.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareNeo-dEb.ttf
          weight: 800
        - asset: assets/fonts/NanumSquareNeo-eHv.ttf
          weight: 900
